extends: google
parserOptions:
  ecmaVersion: 6

rules:
  max-len:
    - 2
    - 80
    - 2
    - ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreStrings: true
  valid-jsdoc: 0
  require-jsdoc: 0
  comma-dangle: 0
  arrow-parens: 0
  semi: 0
  space-before-function-paren: 0
  quotes: 0
  indent:
    - warn
    - 2

env:
  browser: true
  node: true

plugins:
  - html
  - import
